import { writeFile } from 'node:fs/promises';
import type { Workshop } from '../schema.js';

/**
 * Converts a Workshop object to a well-structured Markdown document.
 */
export function exportToMarkdown(workshop: Workshop): string {
  const lines: string[] = [];

  // 1. Header: Workshop title as H1, then metadata block
  lines.push(`# ${workshop.title}\n`);
  
  // Metadata block
  lines.push(`**Topic:** ${workshop.topic}\n`);
  lines.push(`**Audience:** ${workshop.audience.level}${workshop.audience.stack ? ` (${workshop.audience.stack})` : ''}\n`);
  lines.push(`**Duration:** ${workshop.duration} minutes\n`);
  
  // Prerequisites
  if (workshop.prerequisites.length > 0) {
    lines.push(`\n**Prerequisites:**\n`);
    workshop.prerequisites.forEach((prereq) => {
      lines.push(`- ${prereq}\n`);
    });
  }
  
  // Context Sources
  if (workshop.context_sources.length > 0) {
    lines.push(`\n**Context Sources:**\n`);
    workshop.context_sources.forEach((source) => {
      lines.push(`- ${source}\n`);
    });
  }
  
  // 2. Table of Contents
  lines.push(`\n---\n\n## Table of Contents\n`);
  workshop.modules.forEach((module, moduleIdx) => {
    lines.push(`${moduleIdx + 1}. **${module.title}** (${module.duration} min)\n`);
    module.sections.forEach((section, sectionIdx) => {
      lines.push(`   ${moduleIdx + 1}.${sectionIdx + 1}. ${section.title} (${section.duration} min)\n`);
    });
  });
  
  lines.push(`\n---\n`);
  
  // 3. Modules
  workshop.modules.forEach((module, moduleIdx) => {
    lines.push(`\n## ${moduleIdx + 1}. ${module.title}\n`);
    
    // Learning Objectives
    if (module.learning_objectives.length > 0) {
      lines.push(`\n**Learning Objectives:**\n`);
      module.learning_objectives.forEach((objective) => {
        lines.push(`- ${objective.text} (${objective.blooms_level})\n`);
      });
    }
    
    lines.push(`\n**Duration:** ${module.duration} minutes\n`);
    
    // 4. Sections
    module.sections.forEach((section, sectionIdx) => {
      lines.push(`\n### ${moduleIdx + 1}.${sectionIdx + 1}. ${section.title}\n`);
      lines.push(`\n**Duration:** ${section.duration} minutes\n`);
      
      // Format depends on section type
      switch (section.type) {
        case 'lecture':
          lines.push(`\n**Talking Points:**\n`);
          section.talking_points.forEach((point) => {
            lines.push(`- ${point}\n`);
          });
          break;
          
        case 'exercise':
          lines.push(`\n${section.instructions}\n`);
          
          // Starter Code
          lines.push(`\n#### Starter Code\n`);
          lines.push(`\n\`\`\`\n${section.starter_code}\n\`\`\`\n`);
          
          // Solution (collapsible)
          lines.push(`\n#### Solution\n`);
          lines.push(`\n<details>\n<summary>Click to reveal solution</summary>\n\n`);
          lines.push(`\`\`\`\n${section.solution}\n\`\`\`\n`);
          lines.push(`\n</details>\n`);
          
          // Hints (collapsible)
          if (section.hints.length > 0) {
            lines.push(`\n#### Hints\n`);
            lines.push(`\n<details>\n<summary>Click to reveal hints</summary>\n\n`);
            section.hints.forEach((hint, idx) => {
              lines.push(`${idx + 1}. ${hint}\n`);
            });
            lines.push(`\n</details>\n`);
          }
          break;
          
        case 'discussion':
          lines.push(`\n**Prompts:**\n`);
          section.prompts.forEach((prompt, idx) => {
            lines.push(`${idx + 1}. ${prompt}\n`);
          });
          break;
          
        case 'checkpoint':
          lines.push(`\n**Questions:**\n`);
          section.questions.forEach((question, idx) => {
            lines.push(`${idx + 1}. ${question}\n`);
          });
          
          // Answers (collapsible)
          lines.push(`\n#### Answers\n`);
          lines.push(`\n<details>\n<summary>Click to reveal answers</summary>\n\n`);
          section.expected_answers.forEach((answer, idx) => {
            lines.push(`${idx + 1}. **Answer:** ${answer}\n`);
            if (section.explanations[idx]) {
              lines.push(`   **Explanation:** ${section.explanations[idx]}\n`);
            }
          });
          lines.push(`\n</details>\n`);
          break;
      }
    });
  });
  
  // 5. Footer
  lines.push(`\n---\n`);
  lines.push(`\n*Generated by Workshop Factory on ${new Date().toISOString()}*\n`);
  
  return lines.join('');
}

/**
 * Exports a Workshop to a Markdown file on disk.
 */
export async function exportToMarkdownFile(
  workshop: Workshop,
  outputPath: string
): Promise<void> {
  const markdown = exportToMarkdown(workshop);
  await writeFile(outputPath, markdown, 'utf-8');
}
